### ISSUE TITLE
whisper_timestamped doesn't work from an URL in CLI

### ISSUE THREAD

**Issue by dchapelet** [linto-ai/whisper-timestamped#140]
Hi,
Here an example with this public URL [http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4](http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4)
=> whisper_timestamped does not see the file.
_It works with URL only from model_
`whisper.transcribe(model, url)`
```
root@f4c3ca308b23:/app# whisper_timestamped http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4 --model tiny.en --language en --device cpu --detect_disfluencies True --vad True --verbose False
Traceback (most recent call last):
  File "/opt/conda/bin/whisper_timestamped", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.10/site-packages/whisper_timestamped/transcribe.py", line 2374, in cli
    assert os.path.isfile(audio_path), f"File {audio_path} does not exist"
AssertionError: File http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4 does not exist
```
Thank you for your help.
David.

**Comment by dchapelet** [comment]
Hi,
Thanks for your emoji but unfortunately I need to be able to use the CLI with a URL.
Do you have a hotfix ?
Thank you very much for your help.
David.
