### ISSUE TITLE
 assert l1 == l2 or l1 == 0, f"Inconsistent number of segments: whisper_segments ({l1}) != timestamped_word_segments ({l2})"

### ISSUE THREAD

**Issue by hinswhale** [linto-ai/whisper-timestamped#205]
I met this problem several times，what can I do to fix it? Thanks
 
```

WARNING:whisper_timestamped:Inconsistent number of segments: whisper_segments (339) != timestamped_word_segments (340)
Traceback (most recent call last):
  File "/usr/local/bin/whisper_timestamped", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/whisper_timestamped/transcribe.py", line 3097, in cli
    result = transcribe_timestamped(
  File "/usr/local/lib/python3.10/dist-packages/whisper_timestamped/transcribe.py", line 296, in transcribe_timestamped
    (transcription, words) = _transcribe_timestamped_efficient(model, audio,
  File "/usr/local/lib/python3.10/dist-packages/whisper_timestamped/transcribe.py", line 920, in _transcribe_timestamped_efficient
    assert l1 == l2 or l1 == 0, f"Inconsistent number of segments: whisper_segments ({l1}) != timestamped_word_segments ({l2})"
AssertionError: Inconsistent number of segments: whisper_segments (339) != timestamped_word_segments (340)
```

**Comment by KillerX** [comment]
I just started seeing this. Did you per chance recently start using a different whisper model?

**Comment by Jeronymous** [comment]
There is an opened discussion on this : https://github.com/linto-ai/whisper-timestamped/discussions/79#discussioncomment-10405887

It seems to be a corner case, that happens when the model transcribe something like just special language tokens (e.g. `<|0.00|><|de|><|de|><|de|><|de|><|de|>...`).

I am just waiting to have a quick way to reproduce this corner case, to be able to fix it safely.
