### ISSUE TITLE
AssertionError: Got empty transcription!

### ISSUE THREAD

**Issue by agorman** [linto-ai/whisper-timestamped#57]
I'm getting a weird error with a long (> 3 hour) videos. Shorter videos seem to output okay. Running the same command with just whisper outputs properly.

`whisper_timestamped --verbose=False --suppress_tokens="" --accurate --model=tiny --fp16=False -o /tmp /tmp/video.mov`

~~~
Traceback (most recent call last):
  File "/usr/local/bin/whisper_timestamped", line 33, in <module>
    sys.exit(load_entry_point('whisper-timestamped==1.11.0', 'console_scripts', 'whisper_timestamped')())
  File "/usr/local/lib/python3.9/site-packages/whisper_timestamped/transcribe.py", line 1928, in cli
    result = transcribe_timestamped(
  File "/usr/local/lib/python3.9/site-packages/whisper_timestamped/transcribe.py", line 235, in transcribe_timestamped
    (transcription, words) = _transcribe_timestamped_naive(model, audio,
  File "/usr/local/lib/python3.9/site-packages/whisper_timestamped/transcribe.py", line 1026, in _transcribe_timestamped_naive
    assert len(tokens), "Got empty transcription!"
AssertionError: Got empty transcription!
~~~

**Comment by agorman** [comment]
Without `--accurate`

`whisper_timestamped --verbose=False --suppress_tokens="" --model=tiny --fp16=False -o /tmp /tmp/video.mov`

~~~
WARNING:whisper_timestamped:Inconsistent number of segments: whisper_segments (2844) != timestamped_word_segments (2817)
Traceback (most recent call last):
  File "/usr/local/bin/whisper_timestamped", line 33, in <module>
    sys.exit(load_entry_point('whisper-timestamped==1.11.0', 'console_scripts', 'whisper_timestamped')())
  File "/usr/local/lib/python3.9/site-packages/whisper_timestamped/transcribe.py", line 1928, in cli
    result = transcribe_timestamped(
  File "/usr/local/lib/python3.9/site-packages/whisper_timestamped/transcribe.py", line 240, in transcribe_timestamped
    (transcription, words) = _transcribe_timestamped_efficient(model, audio,
  File "/usr/local/lib/python3.9/site-packages/whisper_timestamped/transcribe.py", line 807, in _transcribe_timestamped_efficient
    assert l1 == l2 or l1 == 0, f"Inconsistent number of segments: whisper_segments ({l1}) != timestamped_word_segments ({l2})"
AssertionError: Inconsistent number of segments: whisper_segments (2844) != timestamped_word_segments (2817)
~~~

**Comment by agorman** [comment]
I can post the video file somewhere if that would help but it's 1.7 GB.

**Comment by agorman** [comment]
Turns out this was just due to a version mismatch. I thought I had the latest version of both whisper and whisper-timestamped but it turns out I need to update both. After updating things are working.

**Comment by Jeronymous** [comment]
Indeed I fixed such problems recently
