### ISSUE TITLE
AssertionError "assert len(segment_tokens_check) < len(segment["tokens"])" with option --accurate

### ISSUE THREAD

**Issue by agorman** [linto-ai/whisper-timestamped#61]
I'm getting some errors and bad results with the latest version. Running the file through the latest whisper gives good results.

If I use `--supress_tokens=""` the process completes but I get a bunch of repeated lines. Using the same command with `--suppress_tokes=-1` I see the following errors. Here are the text results to get an idea of the repeated lines.

Let me know what other information would be helpful.

[whisper_timestamped.txt](https://github.com/linto-ai/whisper-timestamped/files/10959638/whisper_timestamped.txt)
[whisper.txt](https://github.com/linto-ai/whisper-timestamped/files/10959639/whisper.txt)

whisper command used
`whisper --verbose=False --suppress_tokens=-1 --model=tiny -o out video.mov`

whisper_timestamped command used
`whisper_timestamped  --accurate --verbose=False --suppress_tokens=-1 --model=tiny -o out video.mov`

~~~
Detected language: English
 98%|?????????????????????????????????????????????????????????????????????????????????????????????????? | 1521171/1557171 [1:04:51<01:32, 390.90frames/s]
Traceback (most recent call last):
  File "/usr/local/bin/whisper_timestamped", line 33, in <module>
    sys.exit(load_entry_point('whisper-timestamped==1.12.1', 'console_scripts', 'whisper_timestamped')())
  File "/usr/local/lib/python3.9/site-packages/whisper_timestamped/transcribe.py", line 2113, in cli
    result = transcribe_timestamped(
  File "/usr/local/lib/python3.9/site-packages/whisper_timestamped/transcribe.py", line 254, in transcribe_timestamped
    (transcription, words) = _transcribe_timestamped_naive(model, audio,
  File "/usr/local/lib/python3.9/site-packages/whisper_timestamped/transcribe.py", line 1150, in _transcribe_timestamped_naive
    assert len(segment_tokens_check) < len(segment["tokens"]) and segment_tokens_check[:-1] == segment["tokens"][:len(segment_tokens_check)-1]
AssertionError
~~~

~~~
Package             Version
------------------- ----------
certifi             2022.12.7
charset-normalizer  3.1.0
cmake               3.25.2
coloredlogs         15.0.1
Cython              0.29.33
dtw-python          1.3.0
ffmpeg-python       0.2.0
filelock            3.9.0
flatbuffers         23.3.3
future              0.18.3
huggingface-hub     0.13.1
humanfriendly       10.0
idna                3.4
lit                 15.0.7
llvmlite            0.39.1
more-itertools      9.1.0
mpmath              1.3.0
numba               0.56.4
numpy               1.23.5
onnxruntime         1.14.1
openai-whisper      20230308
packaging           23.0
pip                 23.0.1
protobuf            4.22.1
PyYAML              6.0
regex               2022.10.31
requests            2.28.2
scipy               1.10.1
setuptools          67.6.0
sympy               1.11.1
tokenizers          0.13.2
torch               1.13.1+cpu
torchaudio          0.13.1
tqdm                4.65.0
transformers        4.26.1
triton              2.0.0
typing_extensions   4.5.0
urllib3             1.26.15
whisper-timestamped 1.12.1
~~~

**Comment by Jeronymous** [comment]
Hello @agorman sorry I missed this issue.
And sorry for the inconvenience.

The real issue to be solved seems to be the assertion error.

I see you don't have the latest version of whisper-timestamped.
Can you first retry with it?

If it still fails, I would need an example to reproduce. Is it possible for you to share the video?

**Comment by agorman** [comment]
@Jeronymous thank you for the response.

I'm still getting an error with `1.12.7`.

`whisper_timestamped --accurate --verbose=False --suppress_tokens=-1 --model=tiny -o /tmp Proxy\ Long\ Beach\ City\ Council\ Meeting\ -\ 7_13_21.mov`

~~~
Traceback (most recent call last):
  File "/usr/local/bin/whisper_timestamped", line 33, in <module>
    sys.exit(load_entry_point('whisper-timestamped==1.12.7', 'console_scripts', 'whisper_timestamped')())
  File "/usr/local/lib/python3.9/site-packages/whisper_timestamped/transcribe.py", line 2153, in cli
    result = transcribe_timestamped(
  File "/usr/local/lib/python3.9/site-packages/whisper_timestamped/transcribe.py", line 254, in transcribe_timestamped
    (transcription, words) = _transcribe_timestamped_naive(model, audio,
  File "/usr/local/lib/python3.9/site-packages/whisper_timestamped/transcribe.py", line 1163, in _transcribe_timestamped_naive
    assert len(segment_tokens_check) < len(segment["tokens"]) and segment_tokens_check[:-1] == segment["tokens"][:len(segment_tokens_check)-1]
~~~

File can be downloaded here https://www.dropbox.com/s/pcdqtvqb65tqm0c/Proxy%20Long%20Beach%20City%20Council%20Meeting%20-%207_13_21.mov?dl=0

~~~
Package             Version
------------------- ----------
certifi             2022.12.7
charset-normalizer  3.1.0
cmake               3.26.0
Cython              0.29.33
dtw-python          1.3.0
ffmpeg-python       0.2.0
filelock            3.10.0
future              0.18.3
idna                3.4
lit                 16.0.0
llvmlite            0.39.1
more-itertools      9.1.0
numba               0.56.4
numpy               1.23.5
openai-whisper      20230314
pip                 23.0.1
regex               2022.10.31
requests            2.28.2
scipy               1.10.1
setuptools          67.6.0
tiktoken            0.3.1
torch               1.13.1+cpu
tqdm                4.65.0
triton              2.0.0
typing_extensions   4.5.0
urllib3             1.26.15
whisper-timestamped 1.12.7
~~~
